version: "3.3"

services:
  
#  web:
#    container_name: web
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on: [ mssql ]
#    ports:
#      - "8080:80"
#  
  
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dotnet-app
    depends_on:
      - app
    links:
      - "app"
  
  app:
    container_name: web_development
    image: "mcr.microsoft.com/dotnet/sdk:3.1"
    depends_on:
      - mssql
    links:
      - "mssql"
    volumes:
      - ./:/app
    command: dotnet watch --project ./app run --urls "http://0.0.0.0:5001"
    ports:
      - "5001:5001"
    networks:
      - dotnet-app
  
  
  mssql: 
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
      SA_PASSWORD: 'GdU5NAXHp+u*CgJD'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Enterprise'
    ports:
      - '1433:1433'
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/secrets:/var/opt/mssql/secrets
    #    user: 0:0
    user: root
    networks:
      - dotnet-app

volumes:
  mssql:
    driver: local

networks:
  dotnet-app:
    driver: bridge